---

- name: Install build dependencies
  apt:
    update_cache: yes
    pkg:
    - python3-pip

- name: Install buildbot
  pip:
    name: "buildbot"
    executable: pip3
    state: present

- name: Install buildbot_extra_pip_packages
  pip:
    name: "{{ buildbot_extra_pip_packages }}"
    executable: pip3
    state: present

- name: Install Amazon Web Services (AWS) SDK
  pip:
    name: "boto3"
    executable: pip3
    state: present

- name: Create /etc/default/buildbot
  template:
    src: Ubuntu.default.j2
    dest: /etc/default/buildbot
    validate: sh -n %s
  notify: Restart buildbot

- name: Create systemd unit
  template:
    src: Ubuntu.systemd.j2
    dest: /lib/systemd/system/buildmaster@.service
    validate: sh -n %s
  notify: Restart buildbot
